apiVersion: v1
kind: Service
metadata:
  name: websvc # 서비스 이름 지정 
spec:
  type: NodePort # 워커 노드의 IP, 실제 외부에서 접속 IP 
  ports:
  - port: 8099 # 서비스 사용 포트 
    targetPort: 80 # 컨테이너 사용 포트 
    protocol: TCP
    nodePort: 30090 # 워커 노드 사용  포트, 실제 외부 접속 IP, 30000-32767 포트 사용
  selector:
    app: webkube